mutation Login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
        user {
            id
            accessToken
            refreshToken
            email
            name
            role
        }
        ok
        errors {
            path
            message
        }
    }
}